// <auto-generated />
namespace FinalProject_cmarek5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StaffDirectory_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StaffDirectory_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202012091922016_StaffDirectory_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
